version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: modulith_db
      POSTGRES_USER: modulith_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/modulith_db
      SPRING_DATASOURCE_USERNAME: modulith_user
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  pgdata:
