spring:
  application:
    name: modulith
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    parameters:
      default.admin.username: ${DEFAULT_ADMIN_USERNAME}
      default.admin.email: ${DEFAULT_ADMIN_EMAIL}
      default.admin.password: ${DEFAULT_ADMIN_PASSWORD}
      default.user.username: ${DEFAULT_USER_USERNAME}
      default.user.email: ${DEFAULT_USER_EMAIL}
      default.user.password: ${DEFAULT_USER_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

logging:
  level:
    org.springframework.modulith: ${LOG_LEVEL_MODULITH}
    org.hibernate.SQL: ${LOG_LEVEL_SQL}
    org.hibernate.type.descriptor.sql: ${LOG_LEVEL_SQL_PARAMS}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration:
      web: ${JWT_ACCESS_EXPIRATION_WEB}      # 15 minutes in milliseconds
      mobile: ${JWT_ACCESS_EXPIRATION_MOBILE}   # 15 minutes in milliseconds
  refresh-token:
    expiration:
      web: ${JWT_REFRESH_EXPIRATION_WEB}    # 1 day in milliseconds
      mobile: ${JWT_REFRESH_EXPIRATION_MOBILE} # 30 days in milliseconds

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED}
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  paths-to-match:
    - /auth/**
    - /users/**

server:
  port: ${SERVER_PORT}

app:
  email:
    from: ${APP_EMAIL_FROM}
  base-url: ${APP_BASE_URL}
  token:
    verification:
      expiration: ${VERIFICATION_TOKEN_EXPIRATION} # 24 hours in milliseconds
    reset-password:
      expiration: ${RESET_PASSWORD_TOKEN_EXPIRATION} # 1 hour in milliseconds
