name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend-next/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend-next/**'
      - '.github/workflows/frontend-ci.yml'

env:
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend-next/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend-next
        npm ci

    - name: Run linter
      run: |
        cd frontend-next
        npm run lint

    - name: Build application
      run: |
        cd frontend-next
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: next-build
        path: frontend-next/.next/

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: frontend-next/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend-next
        npm ci

    - name: Build application
      run: |
        cd frontend-next
        npm run build

    - name: Serve and run Lighthouse CI
      run: |
        cd frontend-next
        npm install -g @lhci/cli
        npm run start &
        sleep 10
        lhci autorun --config=./lighthouserc.json || true
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
